#pragma once

#include "NativeGameplayTags.h"

namespace DustGameplayTags
{
	DUST_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Gameplay_AbilityInputBlocked)
	
	DUST_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Action_Move)
	DUST_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Action_Look)
	DUST_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Action_Jump)
	DUST_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Action_Aim)
	
	DUST_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_Aiming)
	DUST_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_Death_Dying)
	DUST_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_Death_Dead)
	
	DUST_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Movement_Mode_Walking)
	
	DUST_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Dust_Damage_Message)
	DUST_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Dust_Elimination_Message)
	
	DUST_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayEvent_Death)
}
